name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: l3build check (plain TeX)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        uses: xu-cheng/texlive-action@v3
        with:
          scheme: full
          run: l3build check -q -H
